language: node_js
node_js:
- 10.16.2
before_install:
- export TZ=Asia/Taipei
install:
- yarn
- cd client && yarn
- cd server && yarn
script:
- cd client && yarn test
- cd server && yarn test
- yarn test-combine && codecov
branches:
  only:
  - master
notifications:
  email: false
