language: node_js
node_js:
- 10.16.2
before_install:
- export TZ=Asia/Taipei
install:
- yarn
script:
- cd client && yarn && yarn test
- cd ..
- cd server && yarn && yarn test-travis
- cd ..
- yarn test-combine && codecov
branches:
  only:
  - master
notifications:
  email: false
